services:
  functions:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    ports:
      - "${MCP_HOST_PORT:-3011}:3000"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}
        aliases:
          - booking-mcp-server

networks:
  my_custom_network:
    external: true