services:
  functions:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: always
    environment:
      - PORT=3000
    ports:
      - "${MCP_HOST_PORT:-3011}:3000"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}
        aliases:
          - booking-mcp-server

networks:
  my_custom_network:
    external: true
